# Generated by Django 4.0.3 on 2022-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_post",
                    models.CharField(max_length=20, verbose_name="Дата публикации"),
                ),
                (
                    "text_post",
                    models.TextField(unique=True, verbose_name="Заголовок поста"),
                ),
                ("link_post", models.URLField(verbose_name="Ссылка на публикацию")),
                (
                    "link_image_post",
                    models.URLField(verbose_name="Ссысылка на картинку"),
                ),
                ("_is_expired", models.BooleanField(default=False)),
            ],
        ),
    ]
