# Generated by Django 4.0.3 on 2022-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_post', models.CharField(max_length=20, verbose_name='Дата публикации')),
                ('text_post', models.TextField(verbose_name='Заголовок поста')),
                ('link_post', models.URLField(unique=True, verbose_name='Ссылка на публикацию')),
                ('link_image_post', models.URLField(verbose_name='Ссылка на картинку')),
                ('_is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
