# Generated by Django 4.0.3 on 2022-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vk',
            name='data_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vk',
            name='link_image_post',
            field=models.URLField(verbose_name='Ссылка на картинку'),
        ),
    ]
