version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    restart: on-failure

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:alpine

  celery:
    build: ./app
    command: celery -A core worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis

  celery-beat:
    build: ./app
    command: celery -A core beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
