# Generated by Django 4.0.3 on 2022-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название аниме')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка на аниме')),
                ('_is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
