# Generated by Django 4.0.3 on 2022-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitch_model',
            name='streamer',
            field=models.CharField(max_length=30, unique=True, verbose_name='Канал твича'),
        ),
    ]
