# Generated by Django 4.0.3 on 2022-05-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyss', '0003_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serials',
        ),
    ]
