# Generated by Django 4.0.3 on 2022-04-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сериала')),
                ('link', models.PositiveIntegerField(verbose_name='ID на ссылку торрента')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Автоматически созданная дата после загрузки элемента базы')),
                ('_is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
