# Generated by Django 4.0.3 on 2022-04-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='link',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID на ссылку торрента'),
        ),
    ]
