# Generated by Django 4.0.3 on 2022-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_undetected_anime', models.CharField(max_length=50, unique=True, verbose_name='Название аниме')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата обнаружения необнаруженного аниме')),
            ],
        ),
    ]
