# Generated by Django 4.0.3 on 2022-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_listanime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listanime',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
