# Generated by Django 4.0.3 on 2022-04-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название сериала, сезон и серия'),
        ),
    ]
