# Generated by Django 4.0.3 on 2022-05-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0003_serial_episode_serial_serial_and_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ('-data',)},
        ),
    ]
