# Generated by Django 4.0.3 on 2022-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0004_alter_serial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Автоматически созданная дата после загрузки элемента базы'),
        ),
    ]
