# Generated by Django 4.0.3 on 2022-04-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtube_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iframe",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="Айфрейм"
                    ),
                ),
                ("_is_expired", models.BooleanField(default=False)),
            ],
        ),
    ]
