# Generated by Django 4.0.3 on 2022-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather_daily", models.JSONField(verbose_name="Данные на неделю")),
                ("diagram", models.TextField(verbose_name="Тег диаграммы")),
            ],
        ),
        migrations.CreateModel(
            name="Weather_Today",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud", models.PositiveSmallIntegerField(verbose_name="Облачность")),
                ("datetime", models.DateTimeField(verbose_name="Дата")),
                (
                    "humidity",
                    models.PositiveSmallIntegerField(verbose_name="Влажность"),
                ),
                ("moon_phase", models.FloatField(verbose_name="Фаза луны")),
                (
                    "_pop",
                    models.PositiveSmallIntegerField(verbose_name="Вероятность влаги"),
                ),
                ("pressure", models.PositiveSmallIntegerField(verbose_name="Давление")),
                ("rain", models.FloatField(verbose_name="Дождь")),
                ("snow", models.FloatField(verbose_name="Снег")),
                ("sunrise", models.DateTimeField(verbose_name="Восход")),
                ("sunset", models.DateTimeField(verbose_name="Закат")),
                ("temp", models.JSONField(verbose_name="Температура")),
                ("uvi", models.FloatField(verbose_name="Ультрафиолетовый индекс")),
                (
                    "weather_description",
                    models.CharField(max_length=20, verbose_name="Состояние погоды"),
                ),
                (
                    "weather_icon",
                    models.CharField(max_length=6, verbose_name="Иконка погоды"),
                ),
                (
                    "weather_main",
                    models.CharField(
                        max_length=10, verbose_name="Группа погодных параметров"
                    ),
                ),
            ],
        ),
    ]
