# Generated by Django 4.0.3 on 2022-04-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0003_alter_weather_today_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_today',
            name='snow',
        ),
    ]
