# Generated by Django 4.0.3 on 2022-04-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0004_remove_weather_today_snow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_today',
            old_name='_pop',
            new_name='pup',
        ),
    ]
