# Generated by Django 4.0.3 on 2022-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weathers", "0005_rename__pop_weather_today_pup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weather",
            name="diagram",
        ),
    ]
