# Generated by Django 4.0.3 on 2022-04-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weathers", "0006_remove_weather_diagram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weather_today",
            name="rain",
        ),
    ]
