# Generated by Django 4.0.3 on 2022-05-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0007_remove_weather_today_rain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather_Today',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='weather_daily',
            new_name='weather_data_cache',
        ),
    ]
