# Generated by Django 4.0.3 on 2022-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название вакансии')),
                ('salary', models.JSONField(verbose_name='Информация по оплате')),
                ('url_id', models.PositiveIntegerField(unique=True, verbose_name='ID https://hh.ru/vacancy/...')),
                ('published', models.CharField(max_length=20, verbose_name='Дата')),
                ('requirement', models.CharField(max_length=150, verbose_name='Подробности')),
                ('_is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
