# Generated by Django 4.0.3 on 2022-04-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pyss", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Weather",
        ),
    ]
