# Generated by Django 4.0.3 on 2022-04-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyss', '0002_delete_weather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
