# Generated by Django 4.0.3 on 2022-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название сериала')),
                ('img', models.PositiveIntegerField(verbose_name='ID картинки сериала')),
                ('serial_and_season', models.CharField(max_length=128, verbose_name='Название сериала и сезона')),
                ('episode', models.CharField(max_length=128, verbose_name='Количество серий либо сезон полностью')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Автоматически созданная дата после загрузки элемента базы')),
                ('_is_expired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
